const WORDS = [
'REACT', 'NATIVE', 'EXPO', 'JAVASCRIPT', 'COMPONENT', 'ESTADO', 'PROPS', 'FUNCIONAL', 'ANDROID', 'IOS',
'MOBILE', 'DESIGN', 'HOOKS', 'ASYNC', 'PROMISE', 'ARRAY', 'OBJETO', 'VARIAVEL', 'FUNCAO', 'SIMULADOR',
'REINICIAR', 'VITORIA', 'DERROTA', 'TENTATIVAS', 'TECLADO', 'INTERFACE', 'SVG', 'ESTILOS', 'LAYOUT', 'USUARIO',
'PORTUGUES', 'BRASIL', 'PERNAMBUCO', 'PORTO', 'DIGITAL', 'GITHUB'
]

const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('')